-- Run this in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/vimusrczrjvefsbljtmf/sql

-- Disable RLS on core tables only
ALTER TABLE IF EXISTS "Reel" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Style" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ProfilPro" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AppConfig" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "profiles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Reservation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "LiveSession" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Produit" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Commande" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Notification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "MessageChat" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CommentaireStyle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Avis" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Annonce" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Client" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ImmobilierListing" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "DemandeProV2" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Panier" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "PointsFidelite" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "SoldeBeautyPay" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CatalogueOption" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "MembreEquipe" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Publication" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CallSignal" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "LiveMessage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "MariaConversation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "DemandefFranchise" DISABLE ROW LEVEL SECURITY;

-- Also try lowercase table names (some Supabase tables use lowercase)
ALTER TABLE IF EXISTS reel DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS style DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profilpro DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS appconfig DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reservation DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS livesession DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS produit DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commande DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notification DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messagechat DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commentairestyle DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS avis DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS annonce DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS client DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS immobilierlisting DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS demandeprov2 DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS panier DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pointsfidelite DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS soldebeautypay DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS catalogueoption DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS membrequipe DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS publication DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS callsignal DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS livemessage DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mariaconversation DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS demandeffranchise DISABLE ROW LEVEL SECURITY;

-- Verify RLS is disabled
SELECT schemaname, tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public' AND rowsecurity = true;
