-- ============================================================
-- FIX COMPLET: RLS + colonnes manquantes
-- Run in Supabase SQL Editor:
-- https://supabase.com/dashboard/project/vimusrczrjvefsbljtmf/sql
-- ============================================================

-- 1. DISABLE RLS (allow public reads for the main app)
ALTER TABLE "AppConfig" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "profiles" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Reel" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Style" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Produit" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Commande" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Reservation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "LiveSession" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ProfilPro" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Client" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ImmobilierListing" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "DemandeProV2" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "MessageChat" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CommentaireStyle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CommentaireStyle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Avis" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user_like" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user_favorite" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "reel_comment" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Panier" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "PointsFidelite" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SoldeBeautyPay" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CatalogueOption" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "MembreEquipe" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Annonce" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Publication" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CallSignal" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "LiveMessage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "MariaConversation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "DemandefFranchise" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationCode" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VisiteVirtuelle" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "UserMemory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "RoutineBeaute" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Repub" DISABLE ROW LEVEL SECURITY;

-- 2. ADD missing columns to Reel table
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS pub_type text DEFAULT 'reel';
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS is_sponsored boolean DEFAULT false;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS music_title text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS music_artist text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS music_url text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS product_name text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS product_img text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS service_id text;
ALTER TABLE "Reel" ADD COLUMN IF NOT EXISTS service_name text;

-- 3. ADD missing columns to Style table
ALTER TABLE "Style" ADD COLUMN IF NOT EXISTS produits_utilises jsonb DEFAULT '[]'::jsonb;
