-- Desactiver RLS sur toutes les tables importantes
ALTER TABLE public."ProfilPro" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Style" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Reel" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Avis" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Reservation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Notification" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."MessageChat" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Commande" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."Produit" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."LiveSession" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."ImmobilierListing" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."AppConfig" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."CallLog" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProPaymentMethod" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."UserSubscription" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."DemandeProV2" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."StyleCategory" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."StyleSubCategory" DISABLE ROW LEVEL SECURITY;
DO $$ DECLARE r RECORD; BEGIN
  FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
    EXECUTE 'ALTER TABLE public."' || r.tablename || '" DISABLE ROW LEVEL SECURITY';
  END LOOP;
END $$;
